#!python

import os
import json

from git import *
from argdeclare import (Commander, option_group, option, arg)

def tagrelease():
    class CLI(Commander):
        '`tagrelease` is a CLI utility for tagging your releases and updating the deployment branch in `circle.yml`.'
        name = 'tagrelease'
        version = '1.0.0'
        default_args = ['tag', '--help']

        @arg('msg',  help="JSON to send to uuid")
        @arg('uuid', help="Dimmer UUID")
        def do_tag(self, opts):
            """
            Tag a release and update the circle.yml config file, this method
            *must be run* within the root of a git initialized directory.
            """

            cwd = os.path.dirname(os.path.realpath(__file__))
            repo = Repo(cwd)
            git  = repo.git

            if repo.is_dirty():
                print("Commit your changes first before tagging...")
            else:
                git.tag()

    app = CLI()
    app.cmdline()

if __name__ == '__main__':
    tagrelease()
